version: '3.8'

services:
  backend:
    image: <backend image tagged for dockerhub>:latest
    environment:
      - DB_HOST=${rds_endpoint}
      - MIGRATE_DB=${migrate}
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000", ">", "app.log", "2>&1"]
  frontend:
    image: <frontend image tagged for dockerhub>:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
