version: '3.8'

services:
  backend:
    image: postig0x/ecomm_back:latest
    environment:
      - DB_HOST=${rds_endpoint}
      - MIGRATE_DB=${migrate}
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000", ">", "app.log", "2>&1"]
  frontend:
    image: postig0x/ecomm_front:latest
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    depends_on:
      - backend
